module.exports.global = require('./global.js')
module.exports.globalGames = require('./globalGames.js')
module.exports.help = require('./help.js')
module.exports.set = require('./set.js')
module.exports.synonym = require('./synonym.js')
module.exports.define = require('./define.js')
module.exports.example = require('./example.js')
